### ISSUE TITLE
R icon oversized

### ISSUE THREAD

**Issue by Hong-Revo** [MikhailArkhipov/vscode-r#1]
First issue 😀

On my screen, all the icons for R files are too big:

![image](https://user-images.githubusercontent.com/11328890/48249643-db718780-e44f-11e8-9d78-c6abf9a49b09.png)

Possibly a high-DPI thing, I'm running a 4K display at 200% resolution.

**Comment by MikhailArkhipov** [comment]
That’s VSCode icon, file it there :-). They have some icon themes you may try and change.

On Nov 8, 2018, at 23:49, Hong Ooi <notifications@github.com<mailto:notifications@github.com>> wrote:


First issue 😀

On my screen, all the icons for R files are too big:

[image]<https://na01.safelinks.protection.outlook.com/?url=https%3A%2F%2Fuser-images.githubusercontent.com%2F11328890%2F48249643-db718780-e44f-11e8-9d78-c6abf9a49b09.png&data=02%7C01%7Cmikhaila%40microsoft.com%7Cf788df3b11d94586160408d64617d0fc%7C72f988bf86f141af91ab2d7cd011db47%7C1%7C0%7C636773465439559174&sdata=u6GvBtMPEsdbKE1M%2Bkl%2BIkwBHFz%2BIky0PCBUMpio8GU%3D&reserved=0>

Possibly a high-DPI thing, I'm running a 4K display at 200% resolution.

**Comment by Hong-Revo** [comment]
OK, so here? https://github.com/Microsoft/vscode/issues

Seems kinda busy.

**Comment by MikhailArkhipov** [comment]
Yes

On Nov 9, 2018, at 09:35, Hong Ooi <notifications@github.com<mailto:notifications@github.com>> wrote:


OK, so here? https://github.com/Microsoft/vscode/issues<https://na01.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2FMicrosoft%2Fvscode%2Fissues&data=02%7C01%7Cmikhaila%40microsoft.com%7C72f0dbfbb1de4f0de09f08d646509898%7C72f988bf86f141af91ab2d7cd011db47%7C1%7C0%7C636773709300919020&sdata=Gqy15Ay7ROJRtoVJ%2FCncMyOqJSvSZMsh%2FwVRMmftQpU%3D&reserved=0>

Seems kinda busy.
