### ISSUE TITLE
CPU at 98% Energy Impact 195%

### ISSUE THREAD

**Issue by franciscolinares** [MikhailArkhipov/vscode-r#10]
Mikhail thank you for bringing the extension to vscode. I just want to share this issue with CPU and Energy resources on my MacBook. Just started today I guess after yesterdays update. Hope this info helps in any way. Best
<img width="912" alt="screenshot 2018-11-27 at 11 02 02 am" src="https://user-images.githubusercontent.com/38727341/49098796-5949d700-f235-11e8-8763-ec4fa3e983c8.png">
<img width="912" alt="screenshot 2018-11-27 at 11 04 07 am" src="https://user-images.githubusercontent.com/38727341/49098810-62d33f00-f235-11e8-8d9c-79b01a6c365f.png">

**Comment by itssimon** [comment]
Having the same issue here! Thanks for your efforts Mikhail!

**Comment by donlelek** [comment]
I have a similar issue in Ubuntu 18.04.1 LTS. As soon a I open an R script, the R-host starts taking over the CPU increasing temperature  and fan usage. Launching the integrated terminal triggers additional R-Host processes and increases CPU usage even more. I love this extension and I hope the issue will be soon fixed. Thanks!

**Comment by MikhailArkhipov** [comment]
Fixed in 0.0.6
