### ISSUE TITLE
'R: Source File' on Windows

### ISSUE THREAD

**Issue by PGS62** [MikhailArkhipov/vscode-r#11]
Hi Mikhail

I'm excited to see RTVS being ported to VS Code, and thanks for your work on this.

Here's a small problem that I'm guessing will be an easy fix. On Windows, if I try: Ctrl+Shift+P > R: Source File then the command issued to the terminal is `source("d:\myfolder\myfile.R")` and not surprisingly that leads to an error:
`Error: '\m' is an unrecognized escape in character string starting ""d:\m"`
The backslashes in the file name need to be replaced with forward slashes do they not?

Philip

**Comment by MikhailArkhipov** [comment]
0.0.4
