### ISSUE TITLE
Can't find .Net core

### ISSUE THREAD

**Issue by ShawnChen1996** [MikhailArkhipov/vscode-r#14]
I am using manjaro and vscode1.30.0
Version: 1.30.0
Commit: c6e592b2b5770e40a98cb9c2715a8ef89aec3d74
Date: 2018-12-11T22:21:33.585Z
Electron: 2.0.12
Chrome: 61.0.3163.100
Node.js: 8.9.3
V8: 6.1.534.41
OS: Linux x64 4.19.8-2-MANJARO
 and R tool seems not able to find dotnet core and keeps telling me it to install it. 
I have install dotnet core 2.1 runtime and later tried dotnet 2.2, but still not work. 
I can start dotnet in my terminal without any problem
and also when i try excute line in terminal using command 'r.executeInTerminal', it returned 'command 'r.executeInTerminal' not found'. the same for the rest commands

**Comment by atusy** [comment]
I have the same environment and the same issue.

**Comment by ShawnChen1996** [comment]
probably the author can tell us how vscode-r look for dotnet and we will see if there is anything we can do. it looks it has something  to do with manjaro?

**Comment by MikhailArkhipov** [comment]
You can set "r.dependencyChecks" to false to bypass .NET discovery. Basically check does this:
```ts
function IsDotNetInstalled(): boolean {
    let dir: string;

    if (os.IsWindows()) {
        const drive = getenv("SystemDrive");
        dir = drive + "\\Program Files\\dotnet\\shared\\Microsoft.NETCore.App";
    } else if(os.IsMac()) {
        dir = "/usr/local/share/dotnet/shared/Microsoft.NETCore.App";
    } else {
        dir = "/usr/share/dotnet/shared/Microsoft.NETCore.App";
    }
    return fs.existsSync(dir);
}
```

**Comment by hongyuanjia** [comment]
It is probably because that on ArchLinux, [`dotnet-runtime`](https://www.archlinux.org/packages/community/x86_64/dotnet-runtime/) package on AUR is installed at `/opt/dotnet/shared/Microsoft.NETCore.App` not `/usr/share/dotnet/shared/Microsoft.NETCore.App`.

**Comment by hongyuanjia** [comment]
Yeah, it is a little bit tricky to handle all variants...

**Comment by ShawnChen1996** [comment]
yesterday I cloned your git can found the function `IsDotNetInstalled` you showed me. I set `r.dependencyChecks` to false. so the dotnet check is bypassed. But it showed that it couldn't find my R interpreter. but I can manually type R in the terminal and use ctrl+enter to exec the code. I researched your code and found it may also have something to do with path, but I am not able to debug. 
```
        #region R Commands
        [JsonRpcMethod("r/getInterpreterPath")]
        public string getInterpreterPath() {
            if (!IsRInstalled()) {
                return null;
            }

            var provider = _services.GetService<IRInteractiveWorkflowProvider>();
            var workflow = provider.GetOrCreate();
            var homePath = workflow.RSessions.Broker.ConnectionInfo.Uri.OriginalString.Replace('/', Path.DirectorySeparatorChar);

            var binPath = RuntimeInformation.IsOSPlatform(OSPlatform.Windows)
                ? Path.Combine("bin", "x64", "R.exe")
                : Path.Combine("bin", "R");

            return Path.Combine(homePath, binPath);
        }

        private bool IsRInstalled() {
            var ris = _services.GetService<IRInstallationService>();
            var engines = ris
                .GetCompatibleEngines(new SupportedRVersionRange(3, 2, 3, 9))
                .OrderByDescending(x => x.Version)
                .ToList();

            return engines.Count > 0;
}
```

I am wondering if it is possible to grep 'dotnet' and 'R' in $path to check if they are installed in all variants

**Comment by MikhailArkhipov** [comment]
Try setting 
```json
"r.dependencyChecks": false
```
