### ISSUE TITLE
Pressing Del in the R terminal brings up close prompt

### ISSUE THREAD

**Issue by Hong-Revo** [MikhailArkhipov/vscode-r#16]
It happens when there is nothing on the commandline, and you press <kbd>Del</kbd>. R brings up the "Save workspace image? [y/n/c]: " prompt.

**Comment by MikhailArkhipov** [comment]
Something odd between Powershell, R and VS Code... Can't repro just in PS or just in R... weird.

**Comment by Hong-Revo** [comment]
I was able to repro this in both the cmd window and Powershell:

![image](https://user-images.githubusercontent.com/11328890/52551408-76ec0d00-2e30-11e9-8776-e63e4960eb36.png)

![image](https://user-images.githubusercontent.com/11328890/52551528-fbd72680-2e30-11e9-9051-299da66c5816.png)

Might have something to do with the Windows version? I'm running Win 10 Enterprise 1809, build 17763.253.

**Comment by Hong-Revo** [comment]
Not Windows-related either... just tried it with R3.4.3 on a DSVM running Ubuntu 16.04, and it segfaulted (!):

![image](https://user-images.githubusercontent.com/11328890/52551866-56bd4d80-2e32-11e9-8ad2-38aa109bbd92.png)

**Comment by MikhailArkhipov** [comment]
OK then, looks like R oddity...
