### ISSUE TITLE
Bug (Possibly): Unable to find R interpreter

### ISSUE THREAD

**Issue by N1h1l1sT** [MikhailArkhipov/vscode-r#18]
The RTVS plugin in VS Code seems unable to locate my R installation.
It is possible that a cleaning programme like ccleaner has messed up with something, but what I do know is that the registry keys for R are there and the directory they point to, exists.

See pictures below.

![1](https://user-images.githubusercontent.com/10076038/52263105-91a11c00-292e-11e9-9fe2-17ef6af44245.png)
![2](https://user-images.githubusercontent.com/10076038/52263106-91a11c00-292e-11e9-9dd1-680085f71e1d.png)
![3](https://user-images.githubusercontent.com/10076038/52263107-91a11c00-292e-11e9-8273-90f3176dab90.png)
![4](https://user-images.githubusercontent.com/10076038/52263108-9239b280-292e-11e9-8d0f-59482b159929.png)

**Comment by Hong-Revo** [comment]
Does uninstalling and reinstalling R help?

**Comment by Hong-Revo** [comment]
Also see #4.

**Comment by MikhailArkhipov** [comment]
Added troubleshooting to https://github.com/MikhailArkhipov/vscode-r/blob/master/README.md. Will try to add some logging too. RTVS occasionally also had trouble finding R. Is installation per user or per computer (i.e. install for all users)?

**Comment by N1h1l1sT** [comment]
It's installed for all users.

**Comment by tmakowski** [comment]
I also have encountered a similar problem. I have R (version 3.5.1) installed from source (tried installing both, into `/usr` and `/usr/local`) and the plugin fails to find this install.

When I installed a R package (version 3.2.3) via an `apt-get` command the behavior changed -- R now works (mostly). I can start a console but I am getting "Unable to start R process" message however after that I can execute commands without any further problems.

Additionally, when I substitute `/usr/lib/R/bin/R` with a symlink to the source compiled binary the VS Code starts the 3.5.1 version of R console giving me the same message on the start-up as mentioned above. This leaves me with the R version I want and generally works, however I don't think it is a good practice to have everything different versions of everything than the binary itself.

Is there something I am missing? Like a configuration step during R installation which causes difference between the two approaches?

**Comment by MikhailArkhipov** [comment]
https://github.com/microsoft/RTVS/issues/3265#issuecomment-361693994 might be useful

**Comment by MikhailArkhipov** [comment]
Try 0.0.9.
```json
"r.interpreterPath": "C:\\Program Files\\R\\R-3.4.3"
```
i.e. root folder. without `bin/x64`

**Comment by gusbemacbe** [comment]
@MikhailArkhipov 

I am using Manjaro Linux. I applied:

```
    "r.interpreterPath": "/usr/bin/radian",
    "r.rpath.linux": "/usr/bin/R",
    "r.rterm.linux": "/usr/bin/radian",
    "r.rterm.option": [""],
```

I have `dotnet-host`, `dotnet-sdk` and `dotnet-runtime` whose version is 5. I have R and `radian` installed. 

AFter all this, I received an error:

```
Unable to start Microsoft.R.Host process. Exception: R host process did not start on the machine. Exception: Unknown error 139
   at Microsoft.R.Host.Client.BrokerServices.WebService.EnsureSuccessStatusCode(HttpResponseMessage response)
   at Microsoft.R.Host.Client.BrokerServices.WebService.GetHttpPutResponseAsync(Uri uri, String requestBody, CancellationToken cancellationToken)
   at Microsoft.R.Host.Client.BrokerServices.WebService.RepeatUntilAuthenticatedAsync[T](Func`2 action, CancellationToken cancellationToken)
   at Microsoft.R.Host.Client.BrokerServices.WebService.HttpPutAsync[TRequest,TResponse](Uri uri, TRequest request, CancellationToken cancellationToken)
   at Microsoft.R.Host.Client.Host.BrokerClient.CreateBrokerSessionAsync(String name, Boolean useRCommandLineArguments, Boolean isInteractive, CancellationToken cancellationToken)
`

**Comment by MikhailArkhipov** [comment]
This is closed issue about Windows, it is better to open separate one. Have a look at https://github.com/MikhailArkhipov/vscode-r/issues/72#issuecomment-859285010 and report what happens if you run host manually. Like `./Microsoft.R.Host --help`
