### ISSUE TITLE
Unable to start R process. "Unknown error: 134"

### ISSUE THREAD

**Issue by stegmueller** [MikhailArkhipov/vscode-r#2]
This is using a standard R install on OSX located in /Library/Frameworks/R.framework/.

R tools output:

```
[Info  - 3:46:17 PM] Available R interpreters:
[Info  - 3:46:17 PM] 	[0] R 3.5
[Info  - 3:46:17 PM] You can specify the desired interpreter index in the R settings
[Info  - 3:46:17 PM] Selected interpreter: [0] R 3.5.

[Info  - 3:46:17 PM] Starting R Process with /Library/Frameworks/R.framework/Versions/3.5/Resources...
[Error - 3:46:19 PM] Connecting to R Workspace failed.
Reason: R session process did not start on the machine 'VSCR'. Exception:  Unknown error: 134

```

**Comment by MikhailArkhipov** [comment]
Which version of MacOS are you running? The error means process that hosts R.dll did not start. Executable is built on OSX 10.13.

**Comment by stegmueller** [comment]
I am on Mojave as well (10.14.2.).

**Comment by MikhailArkhipov** [comment]
Installed 10.14 on MBP

![image](https://user-images.githubusercontent.com/12820357/48743004-1c1e8d00-ec16-11e8-8f6b-90c28a36e7ec.png)

What happens if you open extension folder in Terminal (in VS Code: Command-Shift-P, then Open Extensions Folder), go to `~/.vscode/extensions/mikhail-arkhipov.r-0.0.1/ls/Host/Mac` and run 
`./Microsoft.R.Host --rhost-help` ? Like this

![image](https://user-images.githubusercontent.com/12820357/48743148-a4049700-ec16-11e8-98df-128cade2f680.png)

**Comment by stegmueller** [comment]
I get
`dyld: Library not loaded: /usr/local/opt/libzip/lib/libzip.5.dylib
  Referenced from: /Users/dstegmue/.vscode-insiders/extensions/mikhail-arkhipov.r-0.0.1/ls/Host/Mac/./Microsoft.R.Host
  Reason: image not found
Abort trap: 6
`

This looks to me like you rely on macports.

**Comment by afreydenzon** [comment]
Yes, thank you. Seemed to be an issue with my libzip introduced by the update (maybe) -- resolved upon a brew uninstall.

![screen shot 2018-11-20 at 11 13 17 am](https://user-images.githubusercontent.com/42430938/48745060-9a7e3c00-ecb5-11e8-9926-0f0f4ac9580a.png)

**Comment by MikhailArkhipov** [comment]
Can you try installing libzip via http://macappstore.org/libzip/ ? If it helps, I'll see what I can do to either include it or automate the install

**Comment by stegmueller** [comment]
Mikhail, I did install libzip via homebrew which fixes the issue.

Can you include brew or ports statements as part of the install? Or you could just list it as a prerequisite (assuming that the union of people using R, VS code, and homebrew or macports is quite large).

**Comment by MikhailArkhipov** [comment]
Most certainly. Extension can look up if library is available and if not, install (if needed) brew and then the package.

**Comment by MikhailArkhipov** [comment]
Automated libzip install in 0.0.2

**Comment by dlill** [comment]
In Ubuntu 18.04, R Tools 0.0.5, I could fix the issue as well by installing `sudo apt-get install libzip4`

**Comment by MikhailArkhipov** [comment]
Yes, that is typically the problem. The extension attempts to install it, but I guess in some cases may fail. If you try and run the host executable from terminal, you'll see more descriptive message typically saying that libzip is missing.

**Comment by donlelek** [comment]
confirming @dlill's finding, installing `libzip4` fixed the issue on 18.04 and 18.10
Thanks

**Comment by oolonek** [comment]
I have the same problem when trying to run R (3.5.1) on a remote Debian (9.1) server accessed via ssh from VSCode

```
[Info  - 4:52:43 PM] Available R interpreters:

[Info  - 4:52:43 PM] 	[0] CRAN R '3.3.3-1'`
[Info  - 4:52:43 PM] You can specify the desired interpreter index in the R settings
[Info  - 4:52:43 PM] Selected interpreter: [0] CRAN R '3.3.3-1'.

[Info  - 4:52:43 PM] Starting R Process with /usr/lib/R...
[Error - 4:52:45 PM] Connecting to R Workspace failed.
Reason: Http request to 'VSCR' has failed.
The machine may be offline or unreachable or  the network has been disconnected.
Error: Response status code does not indicate success: 503 (Service Unavailable).

```

How can I manually specify my R path ?
I tried to look for the `Microsoft.R.Host.Broker.Config.json` file but I dont find it.

How should I proceed here ?

**Comment by MikhailArkhipov** [comment]
JSON config does not exist by default, you need to create it next to the broker executable. You can also try and run broker manually just to check if it fails b/c of some missing dependency or in case it is not marked as executable. See also https://github.com/microsoft/RTVS/issues/3265#issuecomment-361693994

**Comment by zhanglj37** [comment]
Hello,

I also have the similar problem when using r tools (r 4.0.1) on win10.

```
[Info  - 4:34:17] Starting R Process with D:\Software\R\R-4.0.1...
[Error - 4:34:19] Connecting to R Workspace failed.
Reason: Http request to 'VSCR' has failed.
The machine may be offline or unreachable or  the network has been disconnected.
Error: Response status code does not indicate success: 502 (No data received from server or forwarder).
```

I have trouble in understanding the reason, how should I solve this error ?

Thanks a lot for your time!

**Comment by isaactpetersen** [comment]
I also receive a similar error on Windows 10:

```
Unable to start Microsoft.R.Host process. Exception: R host process did not start on the machine. Exception: Unknown error (0xc0000005)
   at Microsoft.R.Host.Client.BrokerServices.WebService.EnsureSuccessStatusCode(HttpResponseMessage response)
   at Microsoft.R.Host.Client.BrokerServices.WebService.GetHttpPutResponseAsync(Uri uri, String requestBody, CancellationToken cancellationToken)
   at Microsoft.R.Host.Client.BrokerServices.WebService.RepeatUntilAuthenticatedAsync[T](Func`2 action, CancellationToken cancellationToken)
   at Microsoft.R.Host.Client.BrokerServices.WebService.HttpPutAsync[TRequest,TResponse](Uri uri, TRequest request, CancellationToken cancellationToken)
   at Microsoft.R.Host.Client.Host.BrokerClient.CreateBrokerSessionAsync(String name, Boolean useRCommandLineArguments, Boolean isInteractive, CancellationToken cancellationToken)
```
