### ISSUE TITLE
Symbol containing dots not supported in autocompletion

### ISSUE THREAD

**Issue by renkun-ken** [MikhailArkhipov/vscode-r#20]
In R, many basic function names contain `.` (e.g., `list.files`, `t.test`), and some package names also do (e.g. `data.table`). The autocompletion does not seem to support any symbol that contains any dot.

**Comment by MikhailArkhipov** [comment]
Not entire sure what is broken

![image](https://user-images.githubusercontent.com/12820357/89090683-6350a100-d359-11ea-9029-473eae62751c.png)

![image](https://user-images.githubusercontent.com/12820357/89090696-75324400-d359-11ea-84b3-2af108918c88.png)

![image](https://user-images.githubusercontent.com/12820357/89090705-867b5080-d359-11ea-9da8-fcf9d86de4f9.png)
