### ISSUE TITLE
Mac: could not find part of path

### ISSUE THREAD

**Issue by adamaltmejd** [MikhailArkhipov/vscode-r#21]
Managed to load the package properly after some trial and error. But now I'm getting the following error when trying to open a terminal/run code:

"Could not find a part of the path '/Library/Frameworks/R.framework/Versions'."

Seems like the package is looking for R in that folder, but my R is installed by Homebrew and the executable is located in /usr/local/bin/R, and accessible as "R" in PATH. How do I change where the extension looks for the executable?

**Comment by MikhailArkhipov** [comment]
See https://github.com/MikhailArkhipov/vscode-r/blob/master/README.md#troubleshooting. I will try and make an easier setting.

**Comment by Hong-Revo** [comment]
Note that on Unices including MacOS, the R in your path is just a shell script. The real binary lives somewhere else.

**Comment by MikhailArkhipov** [comment]
Yes, that is the problem. We don't need the script or R executable. We need location of R.dll and friends.

**Comment by adamaltmejd** [comment]
Not sure I follow. Do I need to create a file called `Microsoft.R.Host.Broker.Config.json` somewhere? What am I supposed to put in there? Homebrew puts R in `/usr/local/Cellar/r/3.5.2_2/` for the latest version but that will change once a new version is released. Am I supposed to update manually every time then?

**Comment by adamaltmejd** [comment]
(the binary in `/usr/local/bin/R´ points to `/usr/local/Cellar/r/3.5.2_2/bin/R`)

**Comment by kizivat** [comment]
I have pretty much the same issue. Where is the extension looking for `Microsoft.R.Host.Broker.Config.json`, please?

**Comment by MikhailArkhipov** [comment]
Next to the executable. Format is in https://github.com/MikhailArkhipov/vscode-r/blob/master/README.md#troubleshooting

**Comment by MikhailArkhipov** [comment]
Try 0.0.9.
```json
"r.interpreterPath": "C:\\Program Files\\R\\R-3.4.3"
```
i.e. root folder. without `bin/x64`
