### ISSUE TITLE
RStudio-like keyboard shortcuts for ` <- ` and ` %>% `

### ISSUE THREAD

**Issue by jackbrookes** [MikhailArkhipov/vscode-r#22]
I use the following snippets but it would be great if these were added to the package (maybe a bit more clever - i.e. trimming the spaces before and after if not needed)

`alt + -`: ` <- `
`ctrl + shift + m`: ` %>% `

My `r.json` user snippets file:
```json
{
	"Assignment operator": {
		"prefix": "Assignment operator",
		"body": " <- "
	},
	"magrittr pipe": {
		"prefix": "magrittr pipe",
		"body": " %>% "
	}

}
```

My custom `keybindings.json` file:

```json
[
    {
        "key": "alt+-",
        "command": "editor.action.insertSnippet",
        "args": { "langId": "r", "name": "Assignment operator" }
    },
    {
        "key": "ctrl+shift+m",
        "command": "editor.action.insertSnippet",
        "args": { "langId": "r", "name": "magrittr pipe" }
    }
]
```

**Comment by MikhailArkhipov** [comment]
Added shortcuts for <- and %>% as suggested in #22. Also, added completion triggers on % and < which allows using completion list for snippets, as in RTVS.

You can either type < and then TAB to get <- via completion list or use keyboard shortcut alt+-. For pipe %>% either type % and then TAB or use ctrl+shift+m shortcut. Snippets file can be found in snippets/r.json in the extension folder.

Thanks to @jackbrookes for suggestions. 👍

**Comment by MikhailArkhipov** [comment]
0.0.12

**Comment by go-bayes** [comment]
@MikhailArkhipov, thank you. This is the magrittr pipe.  How might we opt for the native R pipe, which would be 

body: " |> "
