### ISSUE TITLE
Error in setwd("~")

### ISSUE THREAD

**Issue by jokervTv** [MikhailArkhipov/vscode-r#24]
Everytime i start the vscode , i receive the error:

Error in setwd("~") : cannot change working directory

  Code: -32000 
[object Object]

Before i update the vscode to 1.31.1 in windows10, anything is good.

Thanks.

**Comment by MikhailArkhipov** [comment]
If you run `setwd("~")` in RGUI what happens?

**Comment by MikhailArkhipov** [comment]
https://github.com/Microsoft/RTVS/issues/3232, VS had setting for the working directory. VS Code currently does not expose one.

![image](https://user-images.githubusercontent.com/12820357/52739311-7913b000-2f85-11e9-8c5a-795294d43177.png)

**Comment by jokervTv** [comment]
Sorry sir, I can't see the line.

![image](https://user-images.githubusercontent.com/29646575/52912511-5539cc80-32ed-11e9-9366-9b1749bc4895.png)

And I reinstall RTVS and R Tools for VS code. The question is still bother me. Maybe there are something wrong on my windows.

I find that RTVS always wrong. The extension is great.

![image](https://user-images.githubusercontent.com/29646575/52912637-fa08d980-32ee-11e9-85fd-e2bdb2a5aadd.png)

Thanks for your reply.
