### ISSUE TITLE
Colourising glitch in function args

### ISSUE THREAD

**Issue by Hong-Revo** [MikhailArkhipov/vscode-r#25]
Specifically, when you have `c("a", "b", ...)` as a default function argument, the strings except for the first one are not coloured as text:

![image](https://user-images.githubusercontent.com/11328890/52995267-36af0f00-346e-11e9-8605-5a37a53d2c48.png)

It only appears to happen when the `c` function is used; you can see that `list` doesn't have this problem.

**Comment by MikhailArkhipov** [comment]
This should go to VS Code. There are no custom colorizers as opposed to VS. VS Code uses TextMate grammar files for languages. I bet same thing happens with stock VSC without any extensions.

**Comment by Hong-Revo** [comment]
Ok, I found this repo:

https://github.com/textmate/r.tmbundle

Should it go there?

**Comment by MikhailArkhipov** [comment]
Sounds right.
