### ISSUE TITLE
Use Radian as R interpreter

### ISSUE THREAD

**Issue by davidaarmstrong** [MikhailArkhipov/vscode-r#26]
On MacOS 10.14.2 with VS Code 1.33.1, I want to use [Radian](https://github.com/randy3k/radian) as my R interpreter instead of the normal R implementation.  The radian executable file is in /usr/local/bin.  I tried using the information in the Readme.md file, but couldn't seem to get it to work.  Namely, I tried making generating the file`Microsoft.R.Broker.Host.Config.json` in the `~/.vscode/extensions/mikhail-arkhipov.r-0.0.6/ls` directory.  In it, I put the following: 

```
{
    "r":{"autoDetect":"false"},
    "r":{"interpreters":[{"name":"radian","basePath":"/usr/local/bin"}]}
}
```

When I open an R terminal I don't get radian, rather I get what I would get if I opened `/usr/bin/R`.  

Could you point me in the right direction?

**Comment by efugier** [comment]
```
"r.rterm.linux": "/usr/bin/radian",
"r.rterm.option": [""],
```

Did the trick for me, `"r.rterm.option": [""],` is used to remove the `--no-save` flag which is unknown to radian !

**Comment by MikhailArkhipov** [comment]
Have a look here https://github.com/microsoft/RTVS/issues/3265#issuecomment-361693994

**Comment by MikhailArkhipov** [comment]
0.0.11
https://github.com/MikhailArkhipov/vscode-r/pull/44
See #34 or change log for how to set it up.
