### ISSUE TITLE
On Fedora extension can't find R interpreter

### ISSUE THREAD

**Issue by DiDeoxy** [MikhailArkhipov/vscode-r#27]
Hey,

So I installed R using `sudo dnf install R` which installs to the default location, then the extension, then the .Net Core 2.1 Runtime. At this point, it says it can't find the R interpreter. I go to the extension's ls folder and create Microsoft.R.Host.Broker.Config.json with:
```
{
"R": {
      	"interpreters": {
                "0": {
                      	"name": "R",
                         "basePath": "/usr/bin/R"
                }
        }
}
}
```
Is this the right location for this file? I had a really hard time figuring out where this file should be and this was my best guess since it already had similar files. I also thought the extension should detect the default R installation so I'm not really sure what is going on.

**Comment by stprior** [comment]
Looks like this is related to #14  - the extension appears to be looking for a debian package for R - see https://github.com/MikhailArkhipov/vscode-r/blob/c36c9db71749bd24e296728569633e430063c0ed/src/Unix/R/Platform/Impl/OS/Linux/InstalledPackageInfo.cs#L27. This doesn't work for distros with other package managers. 
I'm not sure what a safe way to look for R across distros would be - possibly running `whereis R` and `R --version`.

**Comment by MikhailArkhipov** [comment]
https://github.com/microsoft/RTVS/issues/3265#issuecomment-361693994 may be useful

**Comment by MikhailArkhipov** [comment]
Try 0.0.9.

"r.interpreterPath": "C:\\Program Files\\R\\R-3.4.3"
i.e. root folder. without bin/x64
