### ISSUE TITLE
Select all text in R Code Chunk

### ISSUE THREAD

**Issue by mkoohafkan** [MikhailArkhipov/vscode-r#28]
VS Code apparently has support for selecting text between e.g. backticks with the command 
```
Ctrl + K + `
```
However, this doesn't seem to be supported in .Rmd files, i.e. I can select all code in an R chunk and send to console. Could this functionality be added?

**Comment by MikhailArkhipov** [comment]
I can't seem to find the command in standard shortcuts. What does the shortcut maps to, i.e. what is the command name?

**Comment by mkoohafkan** [comment]
Oops, turns out this shortcut is provided by an extension: https://marketplace.visualstudio.com/items?itemName=dbankier.vscode-quick-select

**Comment by mkoohafkan** [comment]
Confirmed that this *mostly* works with the quick-select extension, see https://github.com/dbankier/vscode-quick-select/issues/26
