### ISSUE TITLE
Question:

### ISSUE THREAD

**Issue by zekeargus** [MikhailArkhipov/vscode-r#31]
Hello. 2 questions please:
1) Are you planning to add variable editor?
2) Wiull this eventually be a replacement for the terrible R-Studio?
Thanks.

**Comment by MikhailArkhipov** [comment]
1. Possibly. Might try and borrow variable explorer from Python extension.
2. A single dev working in spare time can't really complete with fully staffed teams... ;-)

**Comment by zekeargus** [comment]
Super. Thank you Mikhail.
