### ISSUE TITLE
Reason: R Services broker process did not start on the machine 'VSCR'

### ISSUE THREAD

**Issue by chrisoswald** [MikhailArkhipov/vscode-r#33]
After installing the extension on windows 10 1903 64bit I get the following error after 
`R: Open Terminal`

[Info  - 13:26:24] Available R interpreters:
[Info  - 13:26:24] 	[0] R 3.6.0
[Info  - 13:26:24] 	[1] Microsoft R Open (3.5.3.0)
[Info  - 13:26:24] 	[2] R 3.5.2
[Info  - 13:26:24] You can specify the desired interpreter index in the R settings
[Info  - 13:26:24] Selected interpreter: [0] R 3.6.0.`
[Info  - 13:26:24] Starting R Process with C:\Program Files\R\R-3.6.0...
[Error - 13:26:24] Connecting to R Workspace failed.
Reason: R Services broker process did not start on the machine 'VSCR'. Exception:  Das System hat keinen Meldungstext für die Meldungsnummer 0x%1 in der Meldungsdatei %2 gefunden
`

In the R Tools Startup Log is written:
`
Checking for .NET Core... OK
Activating R Language Server...
Startup completed.
`

Any suggestions what I can do?

Thanks,
Christian

**Comment by DanielReid** [comment]
I have exactly the same issue on Ubuntu 19.10 - fresh install of the extension in vscode, after installing the .NET core runtime manually.

What is the 'VSCR' machine? Should I be updating a key somewhere manually?

**Comment by MikhailArkhipov** [comment]
Might be the same as https://github.com/MikhailArkhipov/vscode-r/issues/30 - key expiration.

**Comment by MikhailArkhipov** [comment]
https://docs.microsoft.com/en-us/visualstudio/rtvs/setting-up-remote-r-workspaces?view=vs-2017#install-an-ssl-certificate-on-ubuntu may help

**Comment by MikhailArkhipov** [comment]
Fixed in 0.0.10
