### ISSUE TITLE
Using radian as R interpreter

### ISSUE THREAD

**Issue by reddy-ia** [MikhailArkhipov/vscode-r#34]
Can anyone please give detailed instructions on specifying path to R console or alternative consoles like radian?

As mentioned [here](https://github.com/MikhailArkhipov/vscode-r/issues/4), I created a file `Microsoft.R.Host.Broker.Config.json` in `~/.vscode/extensions/mikhail-arkhipov.r-0.0.6/ls` folder and specified the following:

![image](https://user-images.githubusercontent.com/52095862/60165385-d0236e80-981c-11e9-846f-452663af9a65.png)

The path specified above leads to radian, an alternative R interpreter. However, when I reloaded the window and open R terminal, it is still opening base R terminal instead of radian.

**Comment by MikhailArkhipov** [comment]
Try 0.0.9.
```json
"r.interpreterPath": "C:\Program Files\R\R-3.4.3"
```
i.e. root folder. without `bin/x64`

**Comment by MikhailArkhipov** [comment]
Extension is not using R executable apart from the terminal. For completions, etc it has to know path to R.dll and related components as it loads R parts into a custom host process then communicates with it over JSON RPC. 

For `Radian` to work there should be 2 separate settings:

- Path to R executable for the terminal
- Path to R version that matches whatever `radian` is using.

**Comment by MikhailArkhipov** [comment]
0.0.11
