### ISSUE TITLE
Not working via Remote SSH

### ISSUE THREAD

**Issue by renkun-ken** [MikhailArkhipov/vscode-r#36]
```
[Info  - 1:05:33 AM] Available R interpreters:
[Info  - 1:05:33 AM] 	[0] CRAN R '3.6.1-3xenial'
[Info  - 1:05:33 AM] You can specify the desired interpreter index in the R settings
[Info  - 1:05:33 AM] Selected interpreter: [0] CRAN R '3.6.1-3xenial'.

[Info  - 1:05:33 AM] Starting R Process with /usr/lib/R...
[Error - 1:05:35 AM] Connecting to R Workspace failed.
Reason: R session process did not start on the machine 'VSCR'. Exception:  Key has expired
```

**Comment by hmassalha** [comment]
same issue !!

**Comment by MikhailArkhipov** [comment]
This has nothing to do with the extension code. Remote access is over SSL and it requires a key. The key had expiration date so if you are using Docker images from RTVS Docker repo, they have pre-generated keys that most probably are now expired. You may have to set up your own remote image or machine as described here: https://docs.microsoft.com/en-us/visualstudio/rtvs/setting-up-remote-r-workspaces?view=vs-2017

**Comment by hmassalha** [comment]
Thanks for your reply. 
I am a data scientist and I just moved to work with vs-code, much powerful environment than Rstudio.

What I can do is the following:
  1. run my code locally (windows OS)
  2. make plots locally (windows OS)
  3. remote connect via SSH to the institute server and run my code to the terminal (thanks for 
      ctrl+enter shortcut)
  4. send jobs using the LSF scheduler

What I can't do and want to have: 
  1. make plots using the remote machine as I am doing locally. I believe it is doable but I am missing something very basic. When I use Rstudio pro (Rstudio that runs on the server and have access via chrome) I can make plots online and see them on my local screen.
*I can save the plots and open then from the remote folder, but not this what I am looking for. As a data scientist, it is very important to have a graphical look at your data before exporting it. 

You might give some hints in your previous comment, and I didn't understand your instructions. 
Thanks, HM

**Comment by Hong-Revo** [comment]
@MikhailArkhipov I think this is basically the same issue as #30.

**Comment by hmassalha** [comment]
Thanks, in #30 they don't have an answer yet !!

**Comment by MikhailArkhipov** [comment]
Same as #30. Working on it.
