### ISSUE TITLE
Exception: System cannot find message text for message number 0x%1 in the message file for %2.

### ISSUE THREAD

**Issue by lucas-fern** [MikhailArkhipov/vscode-r#45]
On windows 10 64 bit I encounter this exception when the extension is starting:

`Unable to start R process. Exception: R Services broker process did not start on the machine '(local)'. Exception: The system cannot find message text for message number 0x%1 in the message file for %2.`

and the R Tools terminal outputs

```
[Info  - 12:51:55 pm] Available R interpreters:
[Info  - 12:51:55 pm] 	[0] R 4.0.2
[Info  - 12:51:55 pm] You can specify the desired interpreter index in the R settings
[Info  - 12:51:55 pm] or provide path to R using `r.interpreterPath` setting.
[Info  - 12:51:55 pm] Selected interpreter: [0] R 4.0.2.

[Info  - 12:51:55 pm] Starting R Process with C:\Program Files\R\R-4.0.2...
```
I've tried reinstalling R and the extension but neither solved anything, any fix?

**Comment by MikhailArkhipov** [comment]
if you open extensions folder (`Ctrl+Shift+P -> Open Extensions ...`), then open command line and try running `Microsoft.R.Host --help` what happens?

![image](https://user-images.githubusercontent.com/12820357/89371157-5c969680-d697-11ea-8cce-c10ce46025b3.png)

![image](https://user-images.githubusercontent.com/12820357/89371190-7932ce80-d697-11ea-8c0b-9dc485008b5f.png)

**Comment by lucas-fern** [comment]
Looks identical to your screencap

![image](https://user-images.githubusercontent.com/35369153/89371430-b09c8c00-d726-11ea-93bb-bbc29a29ed0c.png)

**Comment by MikhailArkhipov** [comment]
OK, let's try to run broker. Go up to `ls` folder and run `Microsoft.R.Host.Broker`

![image](https://user-images.githubusercontent.com/12820357/89380293-1e57a200-d6ac-11ea-859b-2e3f485666af.png)

**Comment by lucas-fern** [comment]
Here is the output

![image](https://user-images.githubusercontent.com/35369153/89380777-738ec480-d73b-11ea-9611-ea1f46fe1eb2.png)

**Comment by MikhailArkhipov** [comment]
Looks normal, broker runs. What's system localе? 
I am also wondering if space in the user name might be a problem... I will try to replicate that.

**Comment by lucas-fern** [comment]
> Looks normal, broker runs. What's system localе?

If I understand correctly, English (Australia)

![image](https://user-images.githubusercontent.com/35369153/89381711-ef3d4100-d73c-11ea-8654-32bca7d18366.png)

**Comment by MikhailArkhipov** [comment]
Can you try installing from VSIX I shared at https://1drv.ms/u/s!Al2G8QsSb4qwgf1BhVgKWs_vZJwqeg?e=AePYd9. I simplified diagnostics a bit so we can get actual exit code.

**Comment by MikhailArkhipov** [comment]
I will publish 0.0.14 with better diagnostics

**Comment by MikhailArkhipov** [comment]
Let me know what 0.0.14 outputs

**Comment by lucas-fern** [comment]
Installing from the .vsix file showed the R Tools settings in my extensions but nothing seemed to happen when opening a .r file. After manually removing those files from `.vscode/extensions` and reinstalling from the marketplace it showed this error.

![image](https://user-images.githubusercontent.com/35369153/89609693-f474ca00-d8bb-11ea-9dbe-84fa40df9396.png)

**Comment by MikhailArkhipov** [comment]
So it _might be_ like you may not have permissions for a program to launch another program. When you launch it manually, it works, but spawn doesn't. Check Windows Event log.

Ex in https://github.com/dotnet/aspnetcore/issues/15580
T**he application-specific permission settings do not grant Local Activation permission** for the COM Server application with CLSID {D63B10C5-BB46-4990-A94F-E40B9D520160} and APPID {9CA88EE3-ACB7-47C8-AFC4-AB702511C276} to the user. **This security permission can be modified using the Component Services administrative tool.**

Another possibility - check `dotnet --version` and make sure runtime is 3.1+.

**Comment by lucas-fern** [comment]
I reinstalled .net and now running 3.1.302 that error has been solved. The extension loads further now but still raises an exception about a minute into `Starting R Process`.

Here's the new output and error;
![image](https://user-images.githubusercontent.com/35369153/89622634-ad480280-d8d6-11ea-801e-d7fdd2e23214.png)

**Comment by MikhailArkhipov** [comment]
Check in task manager if `Microsoft.R.Host.Broker` and `Microsoft.R.Host` are running. The former may also appear as `dotnet Microsoft.R.Host.Broker`. Also, see if there are any crashes reported in windows event log on `Microsoft.R.Host`. like this

![image](https://user-images.githubusercontent.com/12820357/89924998-a0b5f980-dbb7-11ea-8f8f-8647149d78da.png)

**Comment by MikhailArkhipov** [comment]
I believe code that caused 
`The system cannot find message text for message number 0x%1 in the message file for %2.` has been since removed.
