### ISSUE TITLE
"Error: command 'r.openTerminal' not found" occurs "if the active file in the editor is not an R file" 

### ISSUE THREAD

**Issue by malcook** [MikhailArkhipov/vscode-r#53]
#7 still occurs "if the active file in the editor is not an R file" as noted in https://github.com/MikhailArkhipov/vscode-r/issues/7#issuecomment-444750375 

i was happy to find the old issue which told this newbie to vscode-r what the workaround was - but i could imagine someone being stumped/blocked even longer than I was.

**Comment by MikhailArkhipov** [comment]
0.0.17
