### ISSUE TITLE
The specified framework 'Microsoft.NETCore.App', version '5.0.0' was not found.

### ISSUE THREAD

**Issue by Fov6363** [MikhailArkhipov/vscode-r#55]
ENV: my computer is windows10, I use vscode and use windows wsl

ERROR: 
![image](https://user-images.githubusercontent.com/16603080/109245124-db614580-781a-11eb-83e8-d90a5ecaede0.png)

dotnet output:
![image](https://user-images.githubusercontent.com/16603080/109245156-ef0cac00-781a-11eb-8eff-e4d28f0ebdca.png)

Thanks guys

**Comment by MikhailArkhipov** [comment]
You need .NET Core Runtime 5.0, looks like you only have 2.1 which is ancient.

**Comment by Fov6363** [comment]
> You need .NET Core Runtime 5.0, looks like you only have 2.1 which is ancient. I'd recommend removing 2.1.
> 
> https://dotnet.microsoft.com/download/dotnet/5.0

Thanks friends, it's R-tools is ok
