### ISSUE TITLE
Extension causes high cpu load

### ISSUE THREAD

**Issue by quantitative-ecologist** [MikhailArkhipov/vscode-r#56]
- Issue Type: `Performance`
- Extension Name: `r`
- Extension Version: `0.0.20`
- OS Version: `Windows_NT x64 10.0.19042`
- VSCode version: `1.54.1`

:warning: Make sure to **attach** this file from your *home*-directory:
:warning:`c:\Users\maxim\AppData\Local\Temp\Mikhail-Arkhipov.r-unresponsive.cpuprofile.txt`

Find more details here: https://github.com/microsoft/vscode/wiki/Explain-extension-causes-high-cpu-load

**Comment by MikhailArkhipov** [comment]
Can you attach actual `unresponsive.cpuprofile.txt` ? Also, if you look in the task manager, which process is taking CPU time - VS Code (node) or `Microsoft.R.LanguageServer`?

**Comment by quantitative-ecologist** [comment]
Good day,

**Comment by MikhailArkhipov** [comment]
Closing then. Extension (VS Code part) is tiny so if it is `code.exe` or 'node` process there is nothing I can do. If you see high consumption from `Microsoft.R.LanguageServer` let me know. Thanks!
