### ISSUE TITLE
code completion 

### ISSUE THREAD

**Issue by codetrainee** [MikhailArkhipov/vscode-r#6]
When trying to explicitly load namespace using `::`, vscode won't activate code completion. 

If we try library("package name") first, we could get the code completion tip, however, no intellisense will be shown after typing a pair of parenthesis. 

OS: windows 10 1809 17763.134
Vscode: 1.29.1

![ezgif com-video-to-gif 1](https://user-images.githubusercontent.com/8357863/48946863-2a0c3f00-ef83-11e8-9b51-e697d179773a.gif)

**Comment by MikhailArkhipov** [comment]
0.0.5
