### ISSUE TITLE
Support raw string of R 4.0

### ISSUE THREAD

**Issue by psychelzh** [MikhailArkhipov/vscode-r#60]
Seemingly, this new feature is solved in `"lintr"`, see [this issue](https://github.com/jimhester/lintr/issues/484#issue-604574564).

The following syntax should throw no lint error.

![image](https://user-images.githubusercontent.com/13306020/112102254-f2f5d900-8be2-11eb-9378-6f985bb19bc5.png)

**Comment by MikhailArkhipov** [comment]
Looks like it is not actually `lintr` since code does not use R package and rather is new R syntax feature. R parser needs to be updated.

**Comment by MikhailArkhipov** [comment]
0.0.21
