### ISSUE TITLE
Extension causes high cpu load

### ISSUE THREAD

**Issue by aline-pacheco** [MikhailArkhipov/vscode-r#63]
- Issue Type: `Performance`
- Extension Name: `r`
- Extension Version: `0.0.23`
- OS Version: `Windows_NT x64 6.3.9600`
- VS Code version: `1.56.0-insider`

:warning: Make sure to **attach** this file from your *home*-directory:
:warning:`c:\Users\Asus\AppData\Local\Temp\Mikhail-Arkhipov.r-unresponsive.cpuprofile.txt`

Find more details here: https://github.com/microsoft/vscode/wiki/Explain-extension-causes-high-cpu-load

**Comment by MikhailArkhipov** [comment]
Please attach the actual file

**Comment by MikhailArkhipov** [comment]
Closing since there no information on the CPU profile.
