### ISSUE TITLE
R 4.1 support

### ISSUE THREAD

**Issue by MikhailArkhipov** [MikhailArkhipov/vscode-r#68]
`R.dll` API has changed in 4.1, extension R host process is not yet capable of handling v14 API.

**Comment by nfmmm** [comment]
Dear Mikhail Arkhipov:
         As you see : R language has released version 4.1.0. It seems that the RTVS plug-in for visual studio  make a error. Thank you so so so much for update the plug-in!
my enviroment:
R : 4.0.1-4.0.4
Visual Studio: 16.9.6
 Warning message:
Connecting to R Workspace failed.
Reason: HTTP error while creating session on the machine 'R 4.1.0'. Exception: 无法连接到远程服务器
Connecting to R Workspace failed.
Reason: HTTP error while creating session on the machine 'R 4.1.0'. Exception: 无法连接到远程服务器
Interactive Window is disconnected from R session.
Open Workspaces window and either select local R interpreter or try connecting to a remote machine.

In the last version ,it maks error like this:
In base::loadNamespace("rtvs", lib.loc = "c:\\program files (x86)\\microsoft visual studio\\2019\\professional\\common7\\ide\\extensions\\3lb0souu.ufg") :
package ‘rtvs’ has no 'package.rds' in Meta/

**Comment by nfmmm** [comment]
Here:
https://github.com/microsoft/RTVS

**Comment by MikhailArkhipov** [comment]
@nfmmm - I am not sure I will be able to update RTVS. I have retired from Microsoft and RTVS is very large and complicated project that is getting pretty hard to maintain, especially that .NET went to 5.0. Many APIs have recently changed in ASP.NET Core. VS also marked several editor interfaces obsolete which means code has to be reworked extensively to work with VS going forward. 

Sorry, VSCode fork is much smaller and does not have all VS interfaces, project or debugger support.

The warning you mentioned is ignorable. It is not an error. Just a warning that there is no description for internal `rtvs` package.

**Comment by nfmmm** [comment]
It seems that I will  choose VS code or I should use R 4.0 and RTVS 1.6. 
Sincerely thank you so so much for your reply. 
Wish you have a happy life.

**Comment by MikhailArkhipov** [comment]
I may get around to RTVS, and it may be possible to maintain it for VS 2019 but it is unlikely to work beyond 2019.

**Comment by nfmmm** [comment]
Thank you for your continuous efforts.

**Comment by MikhailArkhipov** [comment]
Published as 0.0.24
