### ISSUE TITLE
Cannot start Rtools in JupyterLab instance connecting with Visual Code Studio

### ISSUE THREAD

**Issue by mbac** [MikhailArkhipov/vscode-r#70]
Hi,

I’m unable to run the extension in a JupyterLab instance to which I connect with Visual Studio Code.

The instance is actually a Azure Machine Learning instance. The error pops up during extension loading and just says:

`Unable to start R process. Exception: No R interpreters installed`

I tried entering the path to R as per `which R` (it’s `/usr/bin/R` in the Azure Ubuntu 18 installation, which is otherwise working fine), but it won’t work either.

Can you please help? Thanks!

**Comment by MikhailArkhipov** [comment]
So did you try using `r.intepreterPath` setting?

**Comment by MikhailArkhipov** [comment]
Might also be issue with Ubuntu 18 https://github.com/MikhailArkhipov/vscode-r/issues/72

**Comment by mbac** [comment]
Thanks for your feedback.

Problem is, I had to stop using the Azure service so I’m unable to try again. However, I did set `r.interpreterPath` to `/usr/bin/R`—my bad, I didn’t mention the parameter explicitly in my first post.

Again, sorry but I’m now unable to try again…
