### ISSUE TITLE
R host built on Ubuntu 20 does not run on 18

### ISSUE THREAD

**Issue by koki-fukatsu14** [MikhailArkhipov/vscode-r#72]
Thank you for reading.When I load R language, I get the following message.
![image](https://user-images.githubusercontent.com/67567188/121621621-75d25580-caa7-11eb-8eea-4bc036e27e8c.png)

Ubuntu 18.04(WSL)
NET5.0 is installed.
R is installed.
![image](https://user-images.githubusercontent.com/67567188/121621875-f85b1500-caa7-11eb-8f1e-43baf0ac20b9.png)

**Comment by koki-fukatsu14** [comment]
output 
![image](https://user-images.githubusercontent.com/67567188/121622535-242aca80-caa9-11eb-90ce-16faed6eb468.png)

**Comment by MikhailArkhipov** [comment]
Try 'Open Extensions folder` command in VSC, then locate `mikhail-arkhipov.r-0.0.25/ls/Host/Linux` and see if `Microsoft.R.Host` is permitted to execute.

**Comment by koki-fukatsu14** [comment]
Thank you for answering.
I'm sorry, I would like to know how to check.

**Comment by koki-fukatsu14** [comment]
Was this okay ..?
```
/mnt/c/Users/hukat/.vscode/extensions/mikhail-arkhipov.r-0.0.24/ls/Host/Linux$ ./Microsoft.R.Host 
./Microsoft.R.Host: /lib/x86_64-linux-gnu/libc.so.6: version `GLIBC_2.28' not found (required by ./Microsoft.R.Host)
```

**Comment by MikhailArkhipov** [comment]
Host is built in Ubuntu 20.4 WSL. Tried 18.04 and it indeed produces `/lib/x86_64-linux-gnu/libc.so.6: version `GLIBC_2.28'`. I may try building on 18 instead and see if 20 will accept the binary.

**Comment by MikhailArkhipov** [comment]
OK, using boost 1.65 and building on Ubuntu 18 produces binary that appears to work on both 18 and 20. Will be updating the extension soon.

**Comment by MikhailArkhipov** [comment]
Rebuilt on U18 so it runs on both 18 and 20. 0.0.25
