### ISSUE TITLE
Shortcuts for <- and %>% are active for every language

### ISSUE THREAD

**Issue by safre19** [MikhailArkhipov/vscode-r#75]
Shortcuts for `<-` and `%>%` are active for every language, not only R files.

![Screen Shot 2021-07-26 at 11 07 02](https://user-images.githubusercontent.com/56228835/127012535-e2c2b412-01b5-46f3-8dbf-4b471894b5d8.png)

Took a look at  `package.json` in the extensions folder, but it seems it should be working only when `langId` is `r`.

![Screen Shot 2021-07-26 at 11 09 25](https://user-images.githubusercontent.com/56228835/127012935-dfefc20d-8dc3-4c32-b72c-83b47b1457e5.png)

My user keybinding json file is empty and I have no user snippets that could interfere with those 2. I'm an Emacs user transferring to VSCode slowly, maybe I have done something wrong in the setup of this extension since I'm a real VS Code noob. 

Thank you in advance for your help.

**Comment by MikhailArkhipov** [comment]
0.0.26.
