### ISSUE TITLE
Unable to start Microsoft.R.Host process. Exception: Unknown error

### ISSUE THREAD

**Issue by shmuhammad2004** [MikhailArkhipov/vscode-r#77]
Hi, Thanks for the great work

I am getting this error.  I just install R Tools and finding this error: 

`Unable to start Microsoft.R.Host process. Exception: HTTP error while creating session on the machine '(local)'. Exception: The server returned status code '404' when status code '101' was expected.
`

![image](https://user-images.githubusercontent.com/38854463/129978515-0fca798e-28be-40df-9736-476e21fddd88.png)

Below is my settings:

 ```
    "r.alwaysUseActiveTerminal": true,  
    "r.rterm.mac": "/Users/shamsuddeenmuhammad/anaconda3/bin/radian",
    "r.bracketedPaste": true,
    "remote.SSH.path": "/home/dock/anaconda3/bin/radian",
    "r.interpreterPath": "/usr/local/bin/R",
    "r.rterm.option": [
        "--no-save",
        "--no-restore",
        "--r-binary=*/Users/shamsuddeenmuhammad/anaconda3/bin/radian"
        ],
    "settingsSync.ignoredExtensions": [
    
    ],
    "settingsSync.ignoredSettings": [
    
    ]
}

```

**Comment by MikhailArkhipov** [comment]
Related https://github.com/MikhailArkhipov/vscode-r/issues/73

**Comment by MikhailArkhipov** [comment]
What happens if you go to the extension folder (`Open Extensions Folder` command) and run `./Microsoft.R.Host --help` in `mikhail-arkhipov.r-0.0.26\ls\Host\Linux` directly?

**Comment by MikhailArkhipov** [comment]
What is in `/usr/local/bin/R`? Extension looks there for `lib/libR.so`. So the path should be like `/user/lib/R`. Normally it looks through installed packages and then into `/var/lib/dpkg/info/r-base-core.list` which has all installation folders.

**Comment by MikhailArkhipov** [comment]
Try 0.30 see if this is still an issue
