### ISSUE TITLE
Launching server using command dotnet failed.

### ISSUE THREAD

**Issue by lisasuosuo** [MikhailArkhipov/vscode-r#88]
after I install the extension,it says:

[Error - 5:08:39 PM] Starting client failed
Launching server using command dotnet failed.

and the dotnet version I use is
![image](https://user-images.githubusercontent.com/21986381/176639455-45c9b530-090d-4101-8ab6-7178ed22da5c.png)

**Comment by MikhailArkhipov** [comment]
https://github.com/dotnet/installer/issues/14103

On Mac you may have to resort to .NET 5 unfortunately

**Comment by MikhailArkhipov** [comment]
Please try 0.30, .NET 6 + R 4.2
