### ISSUE TITLE
Lambda support

### ISSUE THREAD

**Issue by marcishak** [MikhailArkhipov/vscode-r#99]
Currently anonymous functions denoted with an `\` instead of a `function` are marked with an unexpected token error.

example:

```
function(x) sum(x) + 1 # no error 

\(x) sum(x) + 1 # unexpected token error 
```

see: https://developer.r-project.org/blosxom.cgi/R-devel/NEWS/2020/12/04#n2020-12-04

**Comment by MikhailArkhipov** [comment]
0.0.32
https://github.com/MikhailArkhipov/vscode-r/releases/tag/0.0.32
